#include <iostream>
#include <iomanip>
#include <string>
#include <map>
#include <string.h>
#include <cstring>
#include <stdio.h>

#define GET_READER_TYPE 			  0x10
#define GET_READER_SERIAL             0x11
#define GET_SERIAL_NUMBER             0x40
#define GET_HARDWARE_VERSION          0x2A
#define GET_FIRMWARE_VERSION          0x29
#define GET_BUILD_NUMBER              0x2B
#define READER_KEY_WRITE              0x12
#define USER_DATA_READ                0x1B
#define USER_DATA_WRITE               0x1C
#define READER_KEYS_LOCK              0x27
#define READER_KEYS_UNLOCK            0x28
#define READER_PASSWORD_WRITE         0x33
#define SELF_RESET                    0x30
#define SET_SPEED_PERMANENTLY         0x4B
#define GET_SPEED_PARAMETERS          0x4C
#define SET_UART_SPEED                0x70
#define RED_LIGHT_CONTROL             0x71
#define USER_INTERFACE_SIGNAL         0x26
#define SET_RF_ANALOG_SETTINGS        0x7D
#define GET_RF_ANALOG_SETTINGS        0x7E
#define SET_LED_CONFIG                0x6E
#define GET_CARD_ID                   0x13
#define GET_CARD_ID_EX                0x2C
#define GET_DLOGIC_CARD_TYPE          0x3C
#define GET_LAST_CARD_ID_EX           0x7C
#define SECTOR_TRAILER_WRITE          0x1A
#define SECTOR_TRAILER_WRITE_UNSAFE   0x2F
#define BLOCK_READ                    0x16
#define BLOCK_WRITE                   0x17
#define BLOCK_IN_SECTOR_READ          0x18
#define BLOCK_IN_SECTOR_WRITE         0x19
#define LINEAR_READ                   0x14
#define LINEAR_WRITE                  0x15
#define LINEAR_FORMAT_CARD            0x25
#define LIN_ROW_READ 				  0x45
#define VALUE_BLOCK_READ              0x1D
#define VALUE_BLOCK_WRITE             0x1E
#define VALUE_BLOCK_INC               0x21
#define VALUE_BLOCK_DEC               0x22
#define VALUE_BLOCK_IN_SECTOR_READ    0x1F
#define VALUE_BLOCK_IN_SECTOR_WRITE   0x20
#define VALUE_BLOCK_IN_SECTOR_INC     0x23
#define VALUE_BLOCK_IN_SECTOR_DEC     0x24
#define GET_DESFIRE_UID               0x80
#define SET_DESFIRE_KEY               0x81
#define DESFIRE_WRITE_TO_FILE         0x82
#define DESFIRE_READ_FROM_FILE        0x83
#define DESFIRE_CREATE_APPLICATION    0x84
#define DESFIRE_CREATE_FILE           0x85
#define DESFIRE_CREATE_AES_KEY        0x86
#define DESFIRE_GET_KEY_CONFIG        0x87
#define DESFIRE_CHANGE_KEY_CONFIG     0x88
#define DESFIRE_DELETE_APPLICATION    0x89
#define DESFIRE_DELETE_FILE           0x8A
#define DESFIRE_SET_CONFIGURATION     0x8B
#define DESFIRE_FORMAT_CARD           0x8C
#define DESFIRE_FREE_MEM              0x8D
#define DESFIRE_WRITE_AES_KEY         0x8E
#define DESFIRE_CREATE_VALUE_FILE     0x8F
#define DESFIRE_READ_VALUE_FILE       0x9A
#define DESFIRE_INCREASE_VALUE_FILE   0x9B
#define DESFIRE_DECREASE_VALUE_FILE   0x9C
#define GET_NFC_T2T_VERSION           0xB0
#define READ_COUNTER                  0xB1
#define INCREMENT_COUNTER             0xB2
#define READ_ECC_SIGNATURE            0xBF
#define SET_CARD_ID_SEND_CONF         0x3D
#define GET_CARD_ID_SEND_CONF         0x3E
#define SET_BAD_SELECT_NR_MAX         0x3F
#define GET_BAD_SELECT_NR_MAX         0x44
#define ENTER_SLEEP_MODE              0x46
#define LEAVE_SLEEP_MODE              0x47
#define AUTO_SLEEP_SET                0x4D
#define AUTO_SLEEP_GET                0x4E
#define SET_DISPLAY_DATA 			  0x72
#define SET_SPEAKER_FREQUENCY 		  0x73
#define SET_DISPLAY_INTENSITY 		  0x74
#define GET_DISPLAY_INTENSITY         0x75
#define UFR_XRC_LOCK_OPEN             0x60
#define UFR_XRC_SET_RELAY_STATE       0x61
#define UFR_XRC_GET_IO_STATE          0x62
#define ENTER_SHARE_RAM_COMM_MODE     0x78
#define EXIT_SHARE_RAM_COMM_MODE      0x79
#define READ_SHARE_RAM                0x7A
#define WRITE_SHARE_RAM               0x7B
#define I_BLOCK_TRANSCEIVE            0x90
#define R_BLOCK_TRANSCEIVE            0x91
#define S_BLOCK_DESELECT              0x92
#define SET_ISO14433_4_MODE           0x93

using namespace std;

map<int, string> FuncMap = {

{0x10,"GET_READER_TYPE"},
{0x11,"GET_READER_SERIAL"},
{0x40,"GET_SERIAL_NUMBER"},
{0x2A,"GET_HARDWARE_VERSION"},
{0x29,"GET_FIRMWARE_VERSION"},
{0x2B,"GET_BUILD_NUMBER"},
{0x12,"READER_KEY_WRITE"},
{0x1B,"USER_DATA_READ"},
{0x1C,"USER_DATA_WRITE"},
{0x27,"READER_KEYS_LOCK"},
{0x28,"READER_KEYS_UNLOCK"},
{0x33,"READER_PASSWORD_WRITE"},
{0x30,"SELF_RESET"},
{0x4B,"SET_SPEED_PERMANENTLY"},
{0x4C,"GET_SPEED_PARAMETERS"},
{0x70,"SET_UART_SPEED"},
{0x71,"RED_LIGHT_CONTROL"},
{0x26,"USER_INTERFACE_SIGNAL"},
{0x7D,"SET_RF_ANALOG_SETTINGS"},
{0x7E,"GET_RF_ANALOG_SETTINGS"},
{0x6E,"SET_LED_CONFIG"},
{0x13,"GET_CARD_ID"},
{0x2C,"GET_CARD_ID_EX"},
{0x3C,"GET_DLOGIC_CARD_TYPE"},
{0x7C,"GET_LAST_CARD_ID_EX"},
{0x1A,"SECTOR_TRAILER_WRITE"},
{0x2F,"SECTOR_TRAILER_WRITE_UNSAFE"},
{0x16,"BLOCK_READ"},
{0x17,"BLOCK_WRITE"},
{0x18,"BLOCK_IN_SECTOR_READ"},
{0x19,"BLOCK_IN_SECTOR_WRITE"},
{0x14,"LINEAR_READ"},
{0x15,"LINEAR_WRITE"},
{0x25,"LINEAR_FORMAT_CARD"},
{0x45,"LIN_ROW_READ"},
{0x1D,"VALUE_BLOCK_READ"},
{0x1E,"VALUE_BLOCK_WRITE"},
{0x21,"VALUE_BLOCK_INC"},
{0x22,"VALUE_BLOCK_DEC"},
{0x1F,"VALUE_BLOCK_IN_SECTOR_READ"},
{0x20,"VALUE_BLOCK_IN_SECTOR_WRITE"},
{0x23,"VALUE_BLOCK_IN_SECTOR_INC"},
{0x24,"VALUE_BLOCK_IN_SECTOR_DEC"},
{0x80,"GET_DESFIRE_UID"},
{0x81,"SET_DESFIRE_KEY"},
{0x82,"DESFIRE_WRITE_TO_FILE"},
{0x83,"DESFIRE_READ_FROM_FILE"},
{0x84,"DESFIRE_CREATE_APPLICATION"},
{0x85,"DESFIRE_CREATE_FILE"},
{0x86,"DESFIRE_CREATE_AES_KEY"},
{0x87,"DESFIRE_GET_KEY_CONFIG"},
{0x88,"DESFIRE_CHANGE_KEY_CONFIG"},
{0x89,"DESFIRE_DELETE_APPLICATION"},
{0x8A,"DESFIRE_DELETE_FILE"},
{0x8B,"DESFIRE_SET_CONFIGURATION"},
{0x8C,"DESFIRE_FORMAT_CARD"},
{0x8D,"DESFIRE_FREE_MEM"},
{0x8E,"DESFIRE_WRITE_AES_KEY"},
{0x8F,"DESFIRE_CREATE_VALUE_FILE"},
{0x9A,"DESFIRE_READ_VALUE_FILE"},
{0x9B,"DESFIRE_INCREASE_VALUE_FILE"},
{0x9C,"DESFIRE_DECREASE_VALUE_FILE"},
{0xB0,"GET_NFC_T2T_VERSION"},
{0xB1,"READ_COUNTER"},
{0xB2,"INCREMENT_COUNTER"},
{0xBF,"READ_ECC_SIGNATURE"},
{0x3D,"SET_CARD_ID_SEND_CONF"},
{0x3E,"GET_CARD_ID_SEND_CONF"},
{0x3F,"SET_BAD_SELECT_NR_MAX"},
{0x44,"GET_BAD_SELECT_NR_MAX"},
{0x46,"ENTER_SLEEP_MODE"},
{0x47,"LEAVE_SLEEP_MODE"},
{0x4D,"AUTO_SLEEP_SET"},
{0x4E,"AUTO_SLEEP_GET"},
{0x72,"SET_DISPLAY_DATA"},
{0x73,"SET_SPEAKER_FREQUENCY"},
{0x74,"SET_DISPLAY_INTENSITY"},
{0x75,"GET_DISPLAY_INTENSITY"},
{0x60,"UFR_XRC_LOCK_OPEN"},
{0x61,"UFR_XRC_SET_RELAY_STATE"},
{0x62,"UFR_XRC_GET_IO_STATE"},
{0x78,"ENTER_SHARE_RAM_COMM_MODE"},
{0x79,"EXIT_SHARE_RAM_COMM_MODE"},
{0x7A,"READ_SHARE_RAM"},
{0x7B,"WRITE_SHARE_RAM"},
{0x90,"I_BLOCK_TRANSCEIVE"},
{0x91,"R_BLOCK_TRANSCEIVE"},
{0x92,"S_BLOCK_DESELECT"},
{0x93,"SET_ISO14433_4_MODE"}

};
